/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package micmacmoe;

import java.util.ArrayList;

public class App {

    public static void main(String... args) {
	var micmacmoe = new Game.Builder()
	    .size(3, 3)
	    .players("X", "O") // @TODO support for AI Player
	    .build();
	//  .playerType(Player.HUMAN)
	 micmacmoe.play();
    }
}
