/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package micmacmoe;

public class App {

    public static void main(String[] args) {
	var micmacmoe = new Game.Builder()
	    .size(3, 3)
	    .players("X", "O") // @TODO support for AI Player 
	    .build();
	micmacmoe.play();
    }
}
